# Generated by Django 4.1.6 on 2023-02-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, max_length=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(max_length=3000)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
