# Generated by Django 4.1.6 on 2023-02-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todorecord_options_alter_todorecord_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todorecord',
            name='body',
            field=models.TextField(max_length=2000),
        ),
    ]
