version: "3.5"

services:
  todo_postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data

  todo_backend:
    build: .
    command: /bin/sh -c "
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput --clear &&
      python manage.py runserver 0.0.0.0:8000 --noreload"
    ports:
      - 8000:8000
    depends_on:
      - todo_postgres
    env_file:
      example.env